dir_backups_base: "/path/to/backups/myapp/"


backup:
  app_files:
    exclude:
      - public/elfinder
      - public/system
      - public/uploads
      - data
      - db


  user_files:
    include:
      - public/uploads
      - public/docs
      - public/images
      - public/img



notify:
  mail:
    from: notify@friendlydata.com
    to: mxdevit@gmail.com
    reply_to: notify@friendlydata.com





storages:
  -
    type: "local"
    path: "/path/to/backups/myapp/"

