

development:
  secret_key_base: xxx
  devise_secret_key: yyy

  db_host: localhost
  db_name: my_cms_tpl
  db_user: root
  db_password: pwd

  redis_host: "localhost"
  redis_port: 6379

  smtp:
    address: 'mail.site.com'
    port: 587
    domain: 'mail.site.com'
    authentication: 'plain'
    user_name: "notify@site.com"
    password: "pwd"
    enable_starttls_auto: true


  slack:
    errors:
      webhook_url: "https://hooks.slack.com/services/hook_code"
      channel: "#channel"
      username: "user"

    general:
      webhook_url: "https://hooks.slack.com/services/hook_code"
      channel: "#channel"
      username: "user"
