# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37efe814db723ddec55249545b2df3f1c807bb40bcbf1509c5a5320facd49487d6744c0a83a6459a7aaa0a949cf06708ead096516724bc91dd5a9b1c8eb1785c

test:
  secret_key_base: faa574034763d6f2873e90ab9e476e672dea8920c5673806b78b7d0f8832c961564bd8fa4d03eb0a8279913f6d0de5273f6c5ba6d930c48dd1c1c6ff43e5d0e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
