default: &default
  repo_app_core: "ssh://git@github.com/myapp.git"
  repo_app_site_data: "ssh://git@github.com/myapp-data.git"

  repo_app_data_dir_name: "repo-data"
  repo_app_data_dir_base: "tmp"

  # dirs to sync
  site_app_data_dirs:
    - app/assets
    - app/views

  # dirs not to sync
  site_user_data_dirs:
    - public/system
    - public/uploads
    - public/img


development:
  <<: *default
  repo_app_data_dir_base: "tmp"


production:
  <<: *default
  repo_app_data_dir_base: "../.."
