
default: &default
  code:
    storage:
      remote_repo: "github.com/maxivak/rails-base-app.git"



development:
  <<: *default

  content:

    -
      name: "views"

      dirs:
        - app/assets
        - app/views


      storage:
        type: git
        remote_repo: "github.com/maxivak/rails-base-app-data.git"
        local_repo_dir: "/data/projects/mysites/site_rails_base_app/repo-data"
        remote_repo_ssh_key: "/data/keys/base_app/id_rsa"




    -
      name: "images"

      dirs:
        - public/img

      exclude:
        - tmp


      storage:
        type: ssh
        host: "mystorage.com"
        ssh_port: 22
        path: "/data/baseapp/repo-images"
        ssh_user: "baseapp"
        ssh_password: "mypass"
        #ssh_key: "/home/myuser/.ssh/id_rsa"



    -
      name: "uploads"

      dirs:
        - public/uploads


      storage:
        type: ssh
        host: "mystorage.com"
        ssh_port: 22
        path: "/data/baseapp/repo-uploads"
        ssh_user: "baseapp"
        ssh_password: "mypass"
        #ssh_key: "/home/myuser/.ssh/id_rsa"








production:
  <<: *default


  content:
    -
      name: "views"

      dirs:
        - app/assets
        - app/views


      storage:
        type: git
        remote_repo: "github.com/maxivak/rails-base-app-data.git"
        local_repo_dir: "/apps/site_rails_base_app/repo-data"
        remote_repo_ssh_key: "/keys/baseapp/id_rsa"



    -
      name: "images"

      dirs:
        - public/img

      exclude:
        - tmp


      storage:
        type: ssh
        host: "mystorage.com"
        ssh_port: 22
        path: "/data/baseapp/repo-images"
        ssh_user: "baseapp"
        #ssh_password: "pwd"
        #ssh_key: "/home/myuser/.ssh/id_rsa"


    -
      name: "uploads"

      dirs:
        - public/uploads

      storage:
        type: ssh
        host: "mystorage.com"
        ssh_port: 22
        path: "/data/baseapp/repo-uploads"
        ssh_user: "baseapp"
        #ssh_password: "pwd"
        #ssh_key: "/home/myuser/.ssh/id_rsa"




